### ISSUE TITLE
Reset button doesnt't work

### ISSUE THREAD

**Issue by CGMossa** [null-ll/basketweave#4]
I've assembled the basketweave.
The reset button makes a noise as if it went to bootloader-mode, but it doesn't do that really.
But if one use the FN + R = Reset, then that works and the keyboard goes fully into bootloader mode.

Any troubleshoot ideas?

Also

* Is there a Keyboard layout that is updated? The one link in [README.md](README.md) doesn't link to the right
layout.
* The qmk configurator isn't setup for the knob -- yet?

**Comment by null-ll** [comment]
To enter bootloader mode, try holding down the BOOT button, tap the RESET button, then let go of both.

I've fixed the [keyboard layout](http://www.keyboard-layout-editor.com/#/gists/9b58a2c896b3cc25a28ef1dc43d93095) link. Thanks for pointing it out. I can't guarantee that the layout is 100% accurate with the distances and locations since I have never had any plates cut using the layout file. 

As far as I know, QMK configurator doesn't support configurating encoders, so you'll have to do this through the firmware files or by using a program like [Vial](https://get.vial.today/).

**Comment by CGMossa** [comment]
Very cool. I'll close this.
